Refactoring Changes on DataLoss Report
hmcts/ccpay-bulkscanning-app pull request #245
Opened 2020-09-08 10:27 UTC by AyanDuttaHMCTS

### JIRA link (if applicable) ###

PAY-2808

### Change description ###

Refactoring Changes on DataLoss Report 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2020-09-08 14:44 UTC, YasharRahvar requested changes

2020-09-08 14:44 UTC, YasharRahvar commented on config/owasp/suppressions.xml
> +  <!--Added on 20th May 2020-->
Do not to add new CVEs unless there is no solution for it at the moment.

2020-09-09 08:46 UTC, AnilDhawaleGitHub approved these changes

2020-09-09 10:09 UTC, aravindan89 approved these changes

2020-09-09 12:34 UTC, AyanDuttaHMCTS commented on config/owasp/suppressions.xml
> +  <!--Added on 20th May 2020-->
Not sure about these CVEs, they exists in last change, But will see if they are valid with recent CVE fixes.

2020-09-29 08:36 UTC, AyanDuttaHMCTS commented on config/owasp/suppressions.xml
> +  <!--Added on 20th May 2020-->
I have checked the CVEs CVE-2017-18640, CVE-2020-8022 we still need to suppress as we are using the following Jars,
snakeyaml-1.25.jar
tomcat-embed-core-9.0.31.jar
tomcat-embed-websocket-9.0.31.jar

2020-10-05 10:31 UTC, YasharRahvar commented on config/owasp/suppressions.xml
> +  <!--Added on 20th May 2020-->
What I mean is to try to upgrade the dependencies and resolve the CVE error instead of suppressing them

2020-10-05 11:45 UTC, AyanDuttaHMCTS commented on config/owasp/suppressions.xml
> +  <!--Added on 20th May 2020-->
These tomcat & snake libs are transitive dependencies of Spring Boot
I think we upgraded Spring Boot for All the Apps.

2020-10-05 11:55 UTC, YasharRahvar approved these changes

2020-10-06 11:07 UTC, krishnanuthalapati approved these changes

2020-10-07 14:17 UTC, merged